version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /caches/app.tar
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: pytest test.py

  build-and-push:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ epoch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.${CIRCLE_BUILD_NUM}
            docker build -t $DOCKER_HUB_USERNAME/myapp:$TAG -f Dockerfile .
      - save_cache:
           paths:
            - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
  
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin
            docker push $DOCKER_HUB_USERNAME/myapp:$TAG

workflows:
  build-deploy:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main  # This ensures the job only runs on the main branch.
