version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest test.py

workflows:
  sample:
    jobs:
      - build-and-test
