version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9  # Ensure this matches the version you need
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # If your requirements.txt is not in the root, specify the directory it is in:
          app-dir: ~/project/subdirectory/  # Update this line with the correct path
          # If your requirements file is named differently, specify the file name:
          pip-dependency-file: subdirectory/requirements.txt  # Update this line with the correct path
      - run:
          name: Run tests
          command: |
            # Adjust the path to pytest if necessary
            pytest ./subdirectory/test.py  # Update this line with the correct path to your test script

workflows:
  sample:
    jobs:
      - build-and-test
