version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: sudo pip install --upgrade pip  # Upgrade pip to the latest version
      - python/install-packages:  # This will automatically use requirements.txt in the root
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest test.py  # Your test script is also in the root directory

workflows:
  sample:
    jobs:
      - build-and-test
