version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9  # Update this line to match the Python version you use
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # Here you can specify a custom directory for your requirements.txt if it's not in the root.
          # For example: app-dir: ~/project/subfolder/
      - run:
          name: Run tests
          command: |
            # If you need to perform additional steps before running pytest, add them here.
            # For example, if you need to install other dependencies or set up your environment.
            # pip install some-other-dependency
            # python some-setup-script.py
            pytest test.py  # Specify the path to your tests if they're not in the root directory

workflows:
  sample:
    jobs:
      - build-and-test
